[project]
name = "nairobi-air-quality-airflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "njuedominic", email = "njuemugodominic@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "apache-airflow==3.3.1",
    "apache-airflow-providers-postgres",
    "requests",
    "psycopg[binary]",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]
